version: '3.8'

services:

  ## --------------------------------------------------
  ## | Web Server - php:8.0.12-apache
  ## --------------------------------------------------
  assignment-core:
    build:
      context: .docker/publisher
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER_ID=${WWW_DATA_USER_ID}
    container_name: assignment-core
    volumes:
      - ./publisher/:/var/www/
      - ./.docker/publisher/config/php.ini:/usr/local/etc/php/php.ini
      - ./.data/publisher/log/webserver:/var/log/apache2
    ports:
      - "${BACKEND_PORT}:80"
    restart: always
    environment:
      - WWW_DATA_USER_ID=${WWW_DATA_USER_ID}
      - EXCLUDE_PORTS=443
    depends_on:
      - assignment-db
      - assignment-queue
    env_file:
      - .env

  ## --------------------------------------------------
  ## | Database - MySQL latest
  ## --------------------------------------------------
  assignment-db:
    image: mysql:latest
    container_name: assignment-db
    volumes:
      - ./.data/database:/var/lib/mysql
    ports:
      - "${DB_HOST_PORT}:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  ## --------------------------------------------------
  ## | Queue - Rabbitmq
  ## --------------------------------------------------
  assignment-queue:
    image: bitnami/rabbitmq
    container_name: assignment-queue
    ports:
      - '${RABBITMQ_HOST_PORT}:15672'
    restart: always
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_NODE_TYPE=queue-disc
    volumes:
      - './.data/rabbitmq:/bitnami'